#!/bin/sh

log() {
    echo "=== [`date`] $*" >> /var/log/docker_maid.log
}

[ ! -S /var/run/docker.sock ] && (log "Error: /var/run/docker.sock not available, bailing."; exit 1)

CONTAINERS=$(docker ps -q -a --filter "status=exited")
if [ ! -z "$CONTAINERS" ]
then
    log "Cleaning unused docker containers:"
    for c in $CONTAINERS
    do
        log "    $c"
    done
    docker rm $CONTAINERS
else
    log "No unused containers found, not cleaning."
fi

# We try to remove all images because there's no reliable way of telling 
# used and unused images apart. Removing used images will fail anyway so 
# it should be fine.
IMAGES=$(docker images -q)
if [ ! -z "$IMAGES" ]
then
    log "Cleaning docker images:"
    for i in $IMAGES
    do
        log "    $i"
    done
    docker rmi $IMAGES || true
else
    log "No unused images found, not cleaning."
fi
